SomethingNew71/classicminidiy

components/torquedocs/index.vue, package-lock.json, package.json
=> :bug: Fixes issue with nm values not showing properly #36

components/electricaldocs/electricaldocs.scss, components/electricaldocs/index.vue, components/navigation/index.vue, components/navigation/navigation.scss, components/pagefoot/index.vue, components/torquedocs/index.vue, nuxt.config.js, package-lock.json, package.json, pages/home.scss, pages/index.vue, pages/manuals/index.vue, pages/manuals/manuals.scss, pages/technical/index.vue
Lots of bug fixes:
#38 
#35 
#34 - I think
Lots of other integration issues with new vuetify but should be good now.
=> Updates to new Vuetify 

assets/styles/app.scss
* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
We must be able to understand the design of your change from this description. If we can't get a good idea of what the code will be doing from the description here, the pull request may be closed at the maintainers' discretion. Keep in mind that the maintainer reviewing this PR may not be familiar with or have worked with the code here recently, so please walk us through the concepts.
Explain why this functionality should be in atom/atom as opposed to a package
What benefits will be realized by the code change?
What are the possible side-effects or negative impacts of the code change?
Enter any applicable Issues …
=> :bug: Forgot my material icons

assets/styles/app.scss, nuxt.config.js
* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
We must be able to understand the design of your change from this description. If we can't get a good idea of what the code will be doing from the description here, the pull request may be closed at the maintainers' discretion. Keep in mind that the maintainer reviewing this PR may not be familiar with or have worked with the code here recently, so please walk us through the concepts.
Explain why this functionality should be in atom/atom as opposed to a package
What benefits will be realized by the code change?
What are the possible side-effects or negative impacts of the code change?
Enter any applicable Issues …
=> :bug: Forget it css will just render block its fonts

pages/manuals/index.vue, pages/technical.vue, pages/technical/colors.vue, pages/technical/electrical.vue, pages/technical/torque.vue
Fixes Issue #57 and a few other things
=> Various bugfixes and attributions additions

components/youtubeSubButton/index.vue, components/youtubeVideos/index.vue, package.json
=> API Fixes and Dev Dependency Updates

pages/youtubers.vue
=> FIxes pauls name typo

pages/technical/electrical.vue
=> Fixes bug with electrical diagrams names

package-lock.json, package.json, pages/technical/needles.vue, pages/technical/torque.vue, pages/technical/wheels.vue
=> Resolves outstanding linting issues and updates npm packages

nuxt.config.js, package-lock.json, package.json
=> Fixes image optimizer, implements ssl redirect tool

nuxt.config.js, package-lock.json, package.json
=> fixes image minification issues

assets/spacing.scss, pages/index.vue
=> Minor visual tweaks to opening header

components/Hero.vue
=> Implements fix for external links not navigating

components/Hero.vue
=> Testing a fix only present in production

nuxt.config.js, package-lock.json, package.json
=> Google Ads - Implement

pages/technical/electrical.vue, pages/technical/index.vue, pages/technical/needles.vue, pages/technical/torque.vue
=> Removes ad's until google finishes site review (COVID-19)

nuxt.config.js, package-lock.json, package.json
=> Moves font-awesome to locally minified and compiled

nuxt.config.js
=> reverts back to including font awesome kit

package-lock.json, package.json
=> Removes font-awesome from npm

package-lock.json, package.json
=> Updates vue-nav-bar with my new changes!

pages/technical/needles.vue
=> Fixes some minor mobile spacing bugs

pages/index.vue
=> Adds contribute button to support section

package-lock.json, package.json
=> Updates nuxt and Beufy

static/data/torqueSpecs.json
- Update Engine, Suspension, Clutch and Gearbox torque specs per Haynes Manual
=> Update To Torque Specs

components/NeedleTable.vue, package-lock.json, package.json, pages/technical/electrical.vue, pages/technical/torque.vue
=> Updates some icons and some dependencies

package-lock.json, package.json
=> Updates some vulnerabilities and highcharts

package-lock.json, package.json
=> Updates sass-loader

components/PatreonPopper.vue
=> Adds some handling for setting cookies if you become a patreon member

pages/technical/colors.vue, pages/technical/electrical.vue, pages/technical/index.vue, pages/technical/manuals.vue, pages/technical/needles.vue, pages/technical/tools.vue, pages/technical/torque.vue
=> Removes OG property images for now

pages/technical/tools.vue
=> Updates colors for headers on tools page

.eslintrc.js, components/CompressionCalculator.vue, components/Hero.vue, pages/technical/compression.vue, pages/technical/index.vue
=> Implements Compression Ratio Calculator

components/CompressionCalculator.vue, pages/technical/compression.vue
=> Compression Ratio calc visual tweaks and sourcing

pages/index.vue
=> Adds CR calc to missing technical section

assets/main.scss, pages/technical/wheels.vue
=> Reorganizes search location and adds contextual help

nuxt.config.js, package-lock.json, package.json, plugins/vue-gtag.js
=> Moves to gtag4 using vue-gtag as a stop gap

components/NeedleConfigurator.vue, nuxt.config.js, package-lock.json, package.json, plugins/highcharts-vue.js, plugins/vue-highcharts.js
=> Updates highcharts module to use official one, updates node modules

components/NeedleConfigurator.vue
=> Implements a live updating method for needle values

pages/technical/wheels.vue
=> Fixes mobile display bug for wheel search

assets/main.scss, components/StorePromo.vue, package-lock.json, package.json, pages/index.vue, pages/technical/compression.vue, pages/technical/needles.vue
=> Adds store page section in place of some ads

pages/technical.vue
=> Adds FB chatbot to other technical pages

components/AdBackfill.vue, layouts/default.vue, pages/technical/index.vue, pages/technical/wheels.vue
=> Removes google ads for a while because it's serving gross ads

nuxt.config.js, pages/technical/colors.vue, pages/technical/compression.vue, pages/technical/electrical.vue, pages/technical/index.vue, pages/technical/needles.vue, pages/technical/torque.vue, pages/technical/wheels.vue
=> Implements pagenation on the wheels page

.npmrc
=> Various fixes to security

package.json, pages/technical/wheels.vue, yarn.lock
=> Implements fuzzy search using fuse.js

static/data/wheels/10.json
=> fixes #249 and #250

components/SpeedoDriveCalculator.vue
=> Adds more options on gearing page

components/CompressionCalculator.vue, static/data/torqueSpecs.json
Adds custom Head Gasket volume and some updated torque specs
Fixes: #275
=> Adds custom Head Gasket volume and some updated torque specs

pages/index.vue
=> Make age programatic
